version: 0.0
os: windows
files:
  - source: \
    destination: C:\Users\Administrator\Desktop\AutoDeploywindow
hooks:
  BeforeInstall:
     - location: build.bat
       runas: Administrator
  AfterInstall:
    - location: run.bat
      runas: Administrator
  ApplicationStart:
    - location: run.bat
      runas: Administrator
      timeout: 4
      - location: openapp.bat
      runas: Administrator
      timeout: 4

